import { Person } from './person';

export const PERSONS: Person[] = [
    {id: 1,
        firstName: 'William',
        lastName: 'Hartnell',
        address: '77 Green street',
        mail: 'whartnell@bbc.com',
        phone: '5550167268'},
    {id: 2,
        firstName: 'Patrick',
        lastName: 'Throughton',
        address: '8922 Stoneway',
        mail: 'pthroughtonl@bbc.com',
        phone: '5550299389'},
    {id: 3,
        firstName: 'John',
        lastName: 'Pertwee',
        address: '178 Color avenue',
        mail: 'jpertwee@bbc.com',
        phone: '5550300894'},
    {id: 4,
        firstName: 'Tom',
        lastName: 'Baker',
        address: '400 Worldwide',
        mail: 'tbaker@bbc.com',
        phone: '5550490009'},
    {id: 5,
        firstName: 'Peter',
        lastName: 'Davison',
        address: '512 Yellowroad',
        mail: 'pdavison@bbc.com',
        phone: '5550519630'},
    {id: 6,
        firstName: 'Colin',
        lastName: 'Baker',
        address: '8080 Longcoat',
        mail: 'cbaker@bbc.com',
        phone: '5550619864'},
    {id: 7,
        firstName: 'Sylvester',
        lastName: 'McCoy',
        address: '7177 Dickens',
        mail: 'smccoy@bbc.com',
        phone: '5550764906'},
    {id: 8,
        firstName: 'Paul',
        lastName: 'McGann',
        address: '8001 American',
        mail: 'pmcgann@bbc.com',
        phone: '5550890102'},
    {id: 9,
        firstName: 'Christopher',
        lastName: 'Eccleston',
        address: '99 Tiger road',
        mail: 'ceccleston@bbc.com',
        phone: '5550920051'},
    {id: 10,
        firstName: 'David',
        lastName: 'Tennant',
        address: '1010 McDonald',
        mail: 'dtennant@bbc.com',
        phone: '5551011233'},
    {id: 11,
        firstName: 'Matt',
        lastName: 'Smith',
        address: '58 Snowball',
        mail: 'msmith@bbc.com',
        phone: '5551104201'},
    {id: 12,
        firstName: 'Peter',
        lastName: 'Capaldi',
        address: '842 Glasgow',
        mail: 'pcapaldi@bbc.com',
        phone: '5551212250'},
    {id: 13,
        firstName: 'Jodie',
        lastName: 'Whittaker',
        address: '1337 Northernshire',
        mail: 'jwhittaker@bbc.com',
        phone: '5551320185'}
];