import { Person } from './person';

export const PERSONS: Person[] = [
    {id: 1,
        firstName: 'William',
        lastName: 'Hartnell',
        address: '77 Green street',
        mail: 'whartnell@bbc.com',
        phone: '55501672685'},
    {id: 2,
        firstName: 'Patrick',
        lastName: 'Throughton',
        address: '8922 Stoneway',
        mail: 'pthroughtonl@bbc.com',
        phone: '55502993892'},
    {id: 3,
        firstName: 'John',
        lastName: 'Pertwee',
        address: '178 Color avenue',
        mail: 'jpertwee@bbc.com',
        phone: '55503008941'},
    {id: 4,
        firstName: 'Tom',
        lastName: 'Baker',
        address: '400 Worldwide',
        mail: 'tbaker@bbc.com',
        phone: '55504900098'},
    {id: 5,
        firstName: 'Peter',
        lastName: 'Davison',
        address: '512 Yellowroad',
        mail: 'pdavison@bbc.com',
        phone: '55505196302'},
    {id: 6,
        firstName: 'Colin',
        lastName: 'Baker',
        address: '8080 Longcoat',
        mail: 'cbaker@bbc.com',
        phone: '55506198644'},
    {id: 7,
        firstName: 'Sylvester',
        lastName: 'McCoy',
        address: '7177 Dickens',
        mail: 'smccoy@bbc.com',
        phone: '55507649065'},
    {id: 8,
        firstName: 'Paul',
        lastName: 'McGann',
        address: '8001 American',
        mail: 'pmcgann@bbc.com',
        phone: '55508901020'},
    {id: 9,
        firstName: 'Christopher',
        lastName: 'Eccleston',
        address: '99 Tiger road',
        mail: 'ceccleston@bbc.com',
        phone: '55509200518'},
    {id: 10,
        firstName: 'David',
        lastName: 'Tennant',
        address: '1010 McDonald',
        mail: 'dtennant@bbc.com',
        phone: '55510112332'},
    {id: 11,
        firstName: 'Matt',
        lastName: 'Smith',
        address: '58 Snowball',
        mail: 'msmith@bbc.com',
        phone: '55511042019'},
    {id: 12,
        firstName: 'Peter',
        lastName: 'Capaldi',
        address: '842 Glasgow',
        mail: 'pcapaldi@bbc.com',
        phone: '55512122500'},
    {id: 13,
        firstName: 'Jodie',
        lastName: 'Whittaker',
        address: '1337 Northernshire',
        mail: 'jwhittaker@bbc.com',
        phone: '55513201856'}
];